name: keyboard_action_form
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'
  flutter: ">=3.12.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.2
  flutter_form_builder: 9.0.0
  flutter_riverpod: 2.3.6
  form_builder_extra_fields: 10.0.0
  keyboard_actions: 4.2.0
  flutter_typeahead: 4.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  custom_lint: 0.4.0
  riverpod_lint: 1.3.2
flutter: