name: keyboard_action_form
version: 0.7.3
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.2"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.8
  form_builder_extra_fields: 12.1.0 
  keyboard_actions: 4.2.0
  flutter_typeahead: 5.2.0
  flutter_form_builder: 10.2.0
  form_builder_validators: 11.2.0
  cooldown_button:
    git:
      url: https://github.com/EdgarJan/cooldown_button.git
      ref: 'de8a1f9'
# dependency_overrides:
#   flutter_typeahead:
#     git:
#       url: https://github.com/EdgarJan/flutter_typeahead
#       ref: 'b9118c5'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
