name: keyboard_action_form
version: 0.6.5
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.3
  form_builder_extra_fields: 10.1.0
  keyboard_actions: 4.2.0
  flutter_typeahead: 4.8.0
  flutter_form_builder: 9.1.1
  form_builder_validators: 9.1.0
  cooldown_button:
    git:
      url: https://github.com/EdgarJan/cooldown_button.git
      ref: 'ef3772e'
dependency_overrides:
  flutter_typeahead:
    git:
      url: https://github.com/EdgarJan/flutter_typeahead
      ref: 'b9118c5'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
flutter: