name: keyboard_action_form
version: 0.3.6
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: 3.0.2
  form_builder_extra_fields: 
    git:
      url: https://github.com/EdgarJan/form_builder_extra_fields.git
      ref: '5273db7' 
  keyboard_actions: 4.2.0
  flutter_typeahead: 4.6.2
  flutter_form_builder:
    git:
      url: https://github.com/EdgarJan/flutter_form_builder.git
      ref: 'df963c90f' 
  form_builder_validators: 9.0.0
  cooldown_button:
    git:
      url: https://github.com/EdgarJan/cooldown_button.git
      ref: '553f688' 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
flutter: